source 'http://rubygems.org'

gem 'sinatra'
gem 'thin'
gem 'activerecord', '5.2', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3', '~> 1.3.6'
gem 'shotgun'
gem 'pry'
gem 'bcrypt'
gem 'tux'