sections_list = {
    "Violin" => {},
    "Viola" => {},
    "Cello" => {},
    "Bass" => {},
    "Oboe" => {},
    "Flute" => {},
    "Clarinet" => {},
    "Bassoon" => {},
    "Trumpet" => {},
    "Horn" => {},
    "Trombone" => {},
    "Tuba" => {},
    "Harp" => {},
    "Percussion" => {},
    "Keyboard" => {},
    "Timpani" => {}
}

sections_list.each do |name, section_hash|
    p = Section.find_or_create_by(name: name)
end 

musicians_list = {
    "Allen Barnhill"    => {section: "Trombone"},
    "Katrina Savitski"  => {section: "Violin"},
    "Wayne Brooks"      => {section: "Viola"},
    "Marina Brubaker"   => {section: "Violin"},
    "Jeffrey Butler"    => {section: "Cello"},
    "Martha Chapman"    => {section: "Violin"},
    "Annie Chen"        => {section: "Violin"},
    "Mihee Chung"       => {section: "Violin"},
    "Rian Craypo"       => {section: "Bassoon"},
    "Brian Del Signore" => {section: "Percussion"},
    "Joan Derhovsepian" => {section: "Viola"},
    "Timothy Dilenschneider" => {section: "Bass"},
    "Judith Dines"      => {section: "Flute"},
    "Adam Dinitz"       => {section: "Oboe"},
    "Aralee Dorough"    => {section: "Flute"},
    "Louis-Marie Fardet" => {section: "Cello"},
    "Jonathan Fischer"  => {section: "Oboe"},
    "Phillip Freeman"   => {section: "Trombone"},
    "Christopher French" => {section: "Cello"},
    "Mihaela Frusina"   => {section: "Violin"},
    "Sergei Galperin"   => {section: "Violin"},
    "Colin Gatwood"     => {section: "Oboe"},
    "Linda Goldstein"   => {section: "Viola"},
    "Rodica Gonzalez"   => {section: "Violin"},
    "Nancy Goodearl"    => {section: "Horn"},
    "Mark Griffith"     => {section: "Percussion"},
    "Eric Halen"        => {section: "Violin"},
    "Richard Harris"    => {section: "Trumpet"},
    "Phyllis Herdliska" => {section: "Viola"},
    "Scott Holshouser"  => {section: "Keyboard"},
    "Donald Howey"      => {section: "Bass"},
    "MuChen Hsieh"      => {section: "Violin"},
    "Mark Hughes"       => {section: "Trumpet"},
    "Wei Jiang"         => {section: "Viola"},
    "Kurt Johnson"      => {section: "Violin"},
    "Robert Johnson"    => {section: "Horn"},
    "Robin Kesselman"   => {section: "Bass"},
    "David Kirk"        => {section: "Tuba"},
    "Anthony Kitai"     => {section: "Cello"},
    "Maki Kubota"       => {section: "Cello"},
    "Kathryn Ladner"    => {section: "Flute"},
    "Si-Yang Lao"       => {section: "Violin"},
    "Eric Larson"       => {section: "Bass"},
    "Hitai Lee"         => {section: "Violin"},
    "Anne Leek"         => {section: "Oboe"},
    "Louis Legrand"     => {section: "Clarinet"},
    "Tianjie Lu"        => {section: "Violin"},
    "Ian Mayton"        => {section: "Horn"},
    "Boson Mo"          => {section: "Violin"},
    "Christopher Neal"  => {section: "Violin"},
    "Jarita Ng"         => {section: "Viola"},
    "Mark Nuccio"       => {section: "Clarinet"},
    "John Parker"       => {section: "Trumpet"},
    "George Pascal"     => {section: "Viola"},
    "Andrew Pedersen"   => {section: "Bass"},
    "Sheldon Person"    => {section: "Viola"},
    "Alexander Potiomkin" => {section: "Clarinet"},
    "Ming Qi"           => {section: "Violin"},
    "Matthew Roitstein" => {section: "Flute"},
    "Christian Schubert" => {section: "Clarinet"},
    "Issac Schultz"     => {section: "Bassoon"},
    "Amy Semes"         => {section: "Violin"},
    "Charles Seo"       => {section: "Cello"},
    "Fay Shapiro"       => {section: "Viola"},
    "Mark Shapiro"      => {section: "Bass"},
    "Burke Shaw"        => {section: "Bass"},
    "Sophia Silivos"    => {section: "Violin"},
    "Yoonshin Song"     => {section: "Violin"},
    "Leonardo Soto"     => {section: "Timpani"},
    "Brinton Smith"     => {section: "Cello"},
    "Matthew Strauss"   => {section: "Percussion"},
    "Daniel Strba"      => {section: "Viola"},
    "Anastasia Sukhopara" => {section: "Violin"},
    "Brian Thomas"      => {section: "Horn"},
    "Yan Tong"          => {section: "Violin"},
    "Adam Trussell"     => {section: "Bassoon"},
    "William Ver Meulen" => {section: "Horn"},
    "Elise Wagner"      => {section: "Bassoon"},
    "Robert Walp"       => {section: "Trumpet"},
    "Bradley White"     => {section: "Trombone"},
    "Xiao Wong"         => {section: "Cello"},
    "Tina Zhang"        => {section: "Violin"},
    "Jing Zheng"        => {section: "Violin"},
    "Megan Conley"      => {section: "Harp"},
    "Ferenc Illenyi"    => {section: "Violin"}
}

musicians_list.each do |name, musician_hash|
    p = Musician.find_or_create_by(name: name)
    p.section = Section.find_by(name: musician_hash[:section])
    p.save
end 

programs_list = {
    "Freedom Over Texas" => {services: 4},
    "Chamber Special 1" => {services: 8},
    "Chamber Special 2" => {services: 6},
    "Chamber Special 3" => {services: 5},
    "Chamber Special 4" => {services: 8},
    "Chamber Special 5" => {services: 8},
    "Chamber Special 6" => {services: 7},
    "Chamber Special 7" => {services: 8},
    "Chamber Special 8" => {services: 8},
    "Pops 1" => {services: 3},
    "Opening Night" => {services: 9},
    "Sub 1" => {services: 8},
    "Sub 2" => {services: 10},
    "Sub 3" => {services: 8}
}

programs_list.each do |name, program_hash|
    p = Program.find_or_create_by(name: name)
    p.services = program_hash[:services]
    p.save 
end

musician_program_list = {
    "Allen Barnhill"    => {programs: [1, 2, 4, 9, 10, 11, 13, ]},
    "Katrina Savitski"  => {programs: [1, 14]},
    "Wayne Brooks"      => {programs: [1, 14]},
    "Marina Brubaker"   => {programs: [1, ]},
    "Jeffrey Butler"    => {programs: [1, ]},
    "Martha Chapman"    => {programs: [1, 14]},
    "Annie Chen"        => {programs: [1, 5, 14]},
    "Mihee Chung"       => {programs: [1, 14]},
    "Rian Craypo"       => {programs: [5, 9, 12, 14]},
    "Brian Del Signore" => {programs: [4, 9, 10, 13]},
    "Joan Derhovsepian" => {programs: [1, 2, 7,  ]},
    "Timothy Dilenschneider" => {programs: [5, 14]},
    "Judith Dines"      => {programs: [2, 9, 13]},
    "Adam Dinitz"       => {programs: [9, 10, 11, ]},
    "Aralee Dorough"    => {programs: [5, 8, 9, 10, 11, ]},
    "Louis-Marie Fardet" => {programs: [1, 3, ]},
    "Jonathan Fischer"  => {programs: [3, 5, 7, 8, 14]},
    "Phillip Freeman"   => {programs: [1, 2, 4, 5, 10, 11, ]},
    "Christopher French" => {programs: [3, 5, 7, 14]},
    "Mihaela Frusina"   => {programs: []},
    "Sergei Galperin"   => {programs: [14]},
    "Colin Gatwood"     => {programs: [3, 5, 8, 14]},
    "Linda Goldstein"   => {programs: []},
    "Rodica Gonzalez"   => {programs: [14]},
    "Nancy Goodearl"    => {programs: [4, 5, 7, 9, 11, 14]},
    "Mark Griffith"     => {programs: [4, 11, ]},
    "Eric Halen"        => {programs: [1, 3, 6, ]},
    "Richard Harris"    => {programs: [1, 2, 4, 9, 10, 11, 13, ]},
    "Phyllis Herdliska" => {programs: []},
    "Scott Holshouser"  => {programs: [1, 2, 6, 10, 11, ]},
    "Donald Howey"      => {programs: [1, ]},
    "MuChen Hsieh"      => {programs: [1, 6, ]},
    "Mark Hughes"       => {programs: [1, 2, 4, 10, 11, 13, ]},
    "Wei Jiang"         => {programs: [3, 6, ]},
    "Kurt Johnson"      => {programs: []},
    "Robert Johnson"    => {programs: []},
    "Robin Kesselman"   => {programs: [3, 8, 14]},
    "David Kirk"        => {programs: [1, 4, 11, 13]},
    "Anthony Kitai"     => {programs: []},
    "Maki Kubota"       => {programs: [1, ]},
    "Kathryn Ladner"    => {programs: [1, 8, 10, ]},
    "Si-Yang Lao"       => {programs: [1, ]},
    "Eric Larson"       => {programs: []},
    "Hitai Lee"         => {programs: [1, ]},
    "Anne Leek"         => {programs: [1, 9, 10, ]},
    "Louis Legrand"     => {programs: [3, 5, 8, 9, 10, ]},
    "Tianjie Lu"        => {programs: []},
    "Ian Mayton"        => {programs: [1, 2, 3, 4, 7, 8, 10, 11, 14]},
    "Boson Mo"          => {programs: [1, 3, 6, ]},
    "Christopher Neal"  => {programs: [1, 6, ]},
    "Jarita Ng"         => {programs: [1, ]},
    "Mark Nuccio"       => {programs: [9, 11, 12, 14]},
    "John Parker"       => {programs: [1, 2, 4, 8, 9, 11]},
    "George Pascal"     => {programs: []},
    "Andrew Pedersen"   => {sprograms: [1, ]},
    "Sheldon Person"    => {programs: [3, 14]},
    "Alexander Potiomkin" => {programs: [1, 3, 5, 8, 10, 11]},
    "Ming Qi"           => {programs: [1, ]},
    "Matthew Roitstein" => {programs: [6, 11, ]},
    "Christian Schubert" => {programs: [9, 14]},
    "Issac Schultz"     => {programs: [3, 8, 9, 11]},
    "Charles Seo"       => {programs: [6, 7, 14]},
    "Amy Semes"         => {programs: [2, 6, ]},
    "Fay Shapiro"       => {programs: [1, ]},
    "Mark Shapiro"      => {programs: []},
    "Burke Shaw"        => {programs: [1, ]},
    "Sophia Silivos"    => {programs: [1, 5, 7, ]},
    "Yoonshin Song"     => {programs: [2, ]},
    "Leonardo Soto"     => {programs: [1, 4, 8, 9, 10]},
    "Brinton Smith"     => {programs: [1, 2, 7, 14]},
    "Matthew Strauss"   => {programs: [1, 3, 4, 5, 10]},
    "Daniel Strba"      => {programs: [14]},
    "Anastasia Sukhopara" => {programs: [1, ]},
    "Brian Thomas"      => {programs: [1, 2, 3, 5, 7, 10, 11]},
    "Yan Tong"          => {programs: [1, ]},
    "Adam Trussell"     => {programs: [2, 9, ]},
    "William Ver Meulen" => {programs: [2, 7, 8, 9, 10, 11, 12, 13, 14]},
    "Elise Wagner"      => {programs: [3, 5, 8, 10, 14]},
    "Robert Walp"       => {programs: [1, 3, 4, 5, 8, 9, 10, 11]},
    "Bradley White"     => {programs: [1, 2, 4, 10, 11]},
    "Xiao Wong"         => {programs: [1, ]},
    "Tina Zhang"        => {programs: [1, ]},
    "Jing Zheng"        => {programs: [1, ]},
    "Megan Conley"      => {programs: [6, 10, 11, 13]},
    "Ferenc Illenyi"    => {programs: []}
}

musician_program_list.each do |name, program_hash|
    p = Musician.find_by(name: name)
    if program_hash[:programs]
        program_hash[:programs].each do |program_id|
            p.programs << Program.find(program_id)
        end 
    end 
    p.save
end 
